USE [master]
GO

/****** Object:  Database [SUCOS_VENDAS]    Script Date: 29/04/2021 19:27:35 ******/
CREATE DATABASE [SUCOS_VENDAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SUCOS_VENDAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SUCOS_VENDAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SUCOS_VENDAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SUCOS_VENDAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SUCOS_VENDAS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ARITHABORT OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SUCOS_VENDAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SUCOS_VENDAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SUCOS_VENDAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SUCOS_VENDAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET RECOVERY FULL 
GO

ALTER DATABASE [SUCOS_VENDAS] SET  MULTI_USER 
GO

ALTER DATABASE [SUCOS_VENDAS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SUCOS_VENDAS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SUCOS_VENDAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SUCOS_VENDAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SUCOS_VENDAS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SUCOS_VENDAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SUCOS_VENDAS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SUCOS_VENDAS] SET  READ_WRITE 
GO

